name = "wechat-article-exporter"
compatibility_date = "2025-10-30"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "KV"
id = "80b881633c3443a0baee86d78c1a79ac"

[[d1_databases]]
binding = "DB"
database_name = "wechat-article-cache"
database_id = "594dd9d5-92c9-4fea-8bcd-76f866a31248"
